spring:
  application:
    name: movie-info-service
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/movie_rest_service?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}




