apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: basic-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-rest
  template:
    metadata:
      labels:
        app: basic-rest
    spec:
      containers:
        - name: basic-rest
          image: am0072008/rest-java-spring:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: mysql-host

---

apiVersion: v1
kind: Service
metadata:
  name: basic-rest-service
spec:
  selector:
    app: basic-rest
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
