apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: am0072008/mysql-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
            - containerPort: 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: basic-rest-secret
                  key: mysql-root-pass
            - name: MYSQL_DATABASE
              value: movie_rest_service
            - name: MYSQL_USER
              valueFrom:
                  secretKeyRef:
                    name: basic-rest-secret
                    key: mysql-user-id
            - name: MYSQL_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: basic-rest-secret
                    key: mysql-user-pass

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306