name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      version: 1.3
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Docker login
        run: docker login -u $docker_username -p $docker_password

      - name: Build mysql image
        run: docker build -t am0072008/mysql-db:$version ./MysqlInfra

      - name: Build spring app image
        run: docker build -t am0072008/rest-java-spring:$version .

      - name: Pushing mysql image
        run: docker push am0072008/mysql-db:$version

      - name: Pushing spring app image
        run: docker push am0072008/rest-java-spring:$version
